2019-11-19 17:49:48,872 file.manager INFO 1.2.0
2019-11-19 17:49:48,872 file.manager INFO Copyright (C) 2003-2010
2019-11-19 17:49:48,874 file.manager INFO   Noriaki Ando
2019-11-19 17:49:48,875 file.manager INFO   Intelligent Systems Research Institute, AIST
2019-11-19 17:49:48,875 file.manager INFO Manager starting.
2019-11-19 17:49:48,877 file.manager INFO Starting local logging.
2019-11-19 17:49:48,881 file.manager.namingmanager INFO NameServer connection succeeded: corba/localhost
2019-11-19 17:49:50,910 file.ManagerServant INFO Master manager not found
2019-11-19 17:49:50,917 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-19 17:49:50,920 file.LocalServiceAdmin INFO All the local services are enabled.
2019-11-19 17:49:50,937 file.manager INFO Component type conf file: Human_Tracking_py.conf loaded.
2019-11-19 17:49:50,948 file.ec_base INFO setRate(1000000.000000) done
2019-11-19 17:49:50,950 file.ec_base INFO setRate(100.000000) done
2019-11-19 17:49:50,953 file.rtobject INFO 1 execution context was created.
2019-11-19 17:49:50,967 file.rtobject INFO Initial active configuration set is default.
2019-11-19 17:49:56,203 file.SdoServiceAdmin WARNING No available SDO service in the factory: 
2019-11-19 17:49:56,203 file.SdoServiceAdmin ERROR type  already exists.
2019-11-19 17:50:03,105 file.ManagerServant INFO Master manager not found
2019-11-19 17:50:15,345 file.ManagerServant INFO Master manager not found
2019-11-19 17:50:23,158 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1571, in on_execute
    ret = self.onExecute(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 176, in onExecute
    a=trans_x_y(1000,300)#(self.range_data[i],i)
TypeError: 'NoneType' object is not callable

2019-11-19 17:50:23,161 file.rtobject ERROR Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\OpenRTM_aist\RTObject.py", line 1370, in on_deactivated
    ret = self.onDeactivated(ec_id)
  File "c:\workspace\Human_Tracking_py\Human_Tracking_py.py", line 163, in onDeactivated
    return RTC.RTC_OK
AttributeError: 'NoneType' object has no attribute 'RTC_OK'

2019-11-19 17:50:27,584 file.ManagerServant INFO Master manager not found
2019-11-19 17:50:28,503 file.ec_worker ERROR State of the RTC is not ACTIVE_STATE.
2019-11-19 17:50:28,513 file.ec_worker WARNING ExecutionContext is already stopped.
2019-11-19 17:50:28,513 file.ec_base ERROR Invoking on_shutdown() for each RTC failed.
